#!/bin/sh
echo 'patching...'

# if jq does not exist, attempt install
if ! [ -x "$(command -v jq)" ]
then
  yum install jq -y
fi

function write_to_plugins () {
  AMPLIFY_PLUGINS_FILE=~/.amplify/plugins.json
  [[ -e $AMPLIFY_PLUGINS_FILE ]] && \
    content="$(jq '.pluginDirectories += ["packaged-node-modules"]' $AMPLIFY_PLUGINS_FILE)" && \
    echo "${content}" > $AMPLIFY_PLUGINS_FILE
}

write_to_plugins